#declaration des variables pour les commandes
ic = "ipconfig/all"
irl = "ipconfig/release"
irn = "ipconfig/renew"
sysinfo = "systeminfo"
osver = "ver"
clear = "cls"
varenv = "set"
check = "chkdsk"
processlist = "tasklist"
